mysite01/urls.py
from django.contrib import admin
from django.urls import path
from app0326 import views, models

urlpatterns = [
    path('admin/', admin.site.urls),
    # 部门管理
    path('depart/add/', views.depart_add),
    path('depart/del/', views.depart_del),
    path('depart/list/', views.depart_list),
    path('depart/<int:nid>/edit/', views.depart_edit),
    # 用户管理
    path('user/list/', views.user_list),
    path('user/add/', views.user_add),
    path('user/<int:nid>/edit/', views.user_edit),
    path('user/<int:nid>/del/', views.user_del),
    # 靓号管理
    path('prettyNum/list/', views.prettyNum_list),
    path('prettyNum/add/', views.prettyNum_add),
]

app0326/models.py
from django.db import models

# Create your models here.

class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name='标题', max_length=32)

    def __str__(self):
        return self.title




class UserInfo(models.Model):
    """员工表"""
    username = models.CharField(verbose_name='姓名', max_length=16)
    password = models.CharField(verbose_name='密码', max_length=32)
    age = models.IntegerField(verbose_name='年龄')
    account = models.DecimalField(verbose_name='账户余额', max_digits=10, decimal_places=2, default=0)
    creat_time = models.DateTimeField(verbose_name='入职时间')
    depart = models.ForeignKey(to='Department', to_field='id', on_delete=models.CASCADE)
    gener_choices = (
        (1, '男'),
        (2, '女'),
    )
    gener = models.SmallIntegerField(verbose_name="性别", choices=gener_choices)


class PrettyNum(models.Model):
    """ 靓号表 """
    mobile = models.CharField(max_length=11, verbose_name='手机号')
    price = models.IntegerField(verbose_name='价格')
    lever_choices = (
        (1, '一级靓号'),
        (2, '二级靓号'),
        (3, '三级靓号'),
        (4, '四级靓号'),
    )
    status_choices = (
        (1, '未售卖'),
        (2, '已售卖'),
    )
    level = models.SmallIntegerField(verbose_name='级别', choices=lever_choices, default=1)
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=2)

app0326/views.py
from django.shortcuts import render, redirect
from app0326 import models
from django import forms
# Create your views here.


def depart_add(request):

    if request.method == 'GET':
        return render(request, 'depart_add.html')

    depar_name = request.POST.get('departname')

    models.Department.objects.create(title=depar_name)

    return redirect('/depart/list/')


def depart_del(request):

    depart_id = request.GET.get('id')
    models.Department.objects.filter(id=depart_id).delete()

    return redirect('/depart/list/')


def depart_list(request):

    depart_object = models.Department.objects.all()

    return render(request, 'depart_list.html', {'depart_obj': depart_object})


def depart_edit(request, nid):

    if request.method == "GET":
        # depart_id = request.GET.get('id')
        depart_object = models.Department.objects.filter(id=nid).first()
        return render(request, 'depart_edit.html',  {'depart_obj': depart_object})


    depart_name = request.POST.get('departname')

    # depart_id = request.GET.get('id')
    models.Department.objects.filter(id=nid).update(title=depart_name)
    return redirect('/depart/list/')



def user_list(request):

    user_object = models.UserInfo.objects.all()
    return render(request, 'user_list.html', {'user_obj': user_object})

##############################################################################

class UserModelForm(forms.ModelForm):
    class Meta:
        model = models.UserInfo
        fields = ['username', 'password', 'age', 'account', 'creat_time', 'depart', 'gener']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.TextInput(attrs={'class': 'form-control'}),
            'age': forms.TextInput(attrs={'class': 'form-control'}),
            'account': forms.TextInput(attrs={'class': 'form-control'}),
            'creat_time': forms.DateTimeInput(attrs={'class': 'form-control'}),
            'depart': forms.Select(attrs={'class': 'form-control'}),
            'gener': forms.Select(attrs={'class': 'form-control'}),

        }
def user_add(request):

    if request.method == 'GET':
        form = UserModelForm()
        return render(request, 'user_add.html', {'form': form})


    form = UserModelForm(data=request.POST)

    # 如果检验成功
    if form.is_valid():
        # print(form.cleaned_data)
        form.save()
        return redirect('/user/list')
    else:
        print(form.errors)
        return render(request, 'user_add.html', {'form': form})



def user_edit(request, nid):

    if request.method == 'GET':
        user_title = models.UserInfo.objects.filter(id=nid).first()
        form = UserModelForm(instance=user_title)
        return render(request, 'user_edit.html', {'form': form})

    user_id = models.UserInfo.objects.filter(id=nid).first()
    form = UserModelForm(data=request.POST, instance=user_id)
    if form.is_valid():
        #增加一些不需要用户输入的值
        # form.instance.字段名 = 值
        form.save()
        return redirect('/user/list')

    return render(request, 'user_edit.html', {'form': form})



def user_del(request, nid):

        models.UserInfo.objects.filter(id=nid).delete()

        return redirect('/user/list/')


################################################ 靓号管理

def prettyNum_list(request):

    PrettyNum_obj = models.PrettyNum.objects.all()

    return render(request, 'prettyNum_list.html', {'PrettyNum': PrettyNum_obj})

class PrettyModelForm(forms.ModelForm):
    class Meta:
        model = models.PrettyNum
        # fields = ['mobile', 'price', 'level', 'status']
        fields = '__all__'
        widgets = {
            'mobile': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'level': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
        }
    # def __int__(self, *args, **kwargs):
    #     super().__int__(*args, **kwargs)
    #     for name, field in self.fields.items():
    #         field.widget.attrs = {'class': 'form-control'}

def prettyNum_add(request):

    if request.method == 'GET':
        form = PrettyModelForm()
        return render(request, 'prettyNum_add.html', {'form': form})

    form = PrettyModelForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('/prettyNum/list/')


    return  render(request, 'prettyNum_add.html', {'form': form})













app0326/templates/depart_add.html
{% extends 'layout.html' %}


{% block contend %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建部门</h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>标题</label>
                        <input type="text" class="form-control" placeholder="标题" name="departname">
                    </div>
                    <input type="submit" class="btn btn-primary" placeholder="添 加">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app0326/templates/depart_edit.html
{% extends 'layout.html' %}



{% block contend %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建部门</h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>标题</label>
                        <input type="text" class="form-control" placeholder="标题" name="departname" value="{{ depart_obj.title }}">
                    </div>
                    <input type="submit" class="btn btn-primary" placeholder="添 加">
                </form>
            </div>
        </div>
    </div>
{% endblock %}


app0326/templates/depart_list.html
{% extends 'layout.html' %}




{% block contend %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/depart/add/">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                新建部门
            </a>
        </div>

       <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
          <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
          部门列表
      </div>

      <!-- Table -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>名称</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
            {% for roe in depart_obj %}
                <tr>
                    <th>{{ roe.id }}</th>
                    <td>{{ roe.title }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/depart/{{ roe.id }}/edit/">编辑</a>
                        <a class="btn btn-danger btn-xs" href="/depart/del/?id={{ roe.id }}">删除</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>

    </div>
{% endblock %}

app0326/templates/info_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>INFO列表</h1>
<table border="1">
    <thead>
        <tr>
            <th>ID</th>
            <th>姓名</th>
            <th>密码</th>
            <th>年龄</th>
        </tr>
    </thead>
    <tbody>
        <a href="/info/add">添加用户</a>
        {% for row in info_object %}
            <tr>
                <td>{{ row.id }}</td>
                <td>{{ row.username }}</td>
                <td>{{ row.password }}</td>
                <td>{{ row.age }}</td>
                <td><a href="/info/del/?id={{ row.id }}">删除</a></td>
            </tr>
        {% endfor %}
    </tbody>

</table>
</body>
</html>

app0326/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'bootstrap-3.4.1-dist/css/bootstrap.min.css' %}">
    <style>
        .navbar{
            border-radius: 0;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">联通用户管理系统</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li><a href="/depart/list/">部门管理</a></li>
          <li><a href="/user/list/">员工管理</a></li>
          <li><a href="/prettyNum/list/">靓号管理</a></li>
        <li><a href="#">Link</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

          <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div>
    {% block contend %}
    {% endblock %}
</div>


<script src="{% static 'jquery-3.7.1.min.js' %}"></script>
<script src="{% static 'bootstrap-3.4.1-dist/js/bootstrap.min.js' %}"></script>
</body>
</html>

app0326/templates/prettyNum_add.html
{% extends 'layout.html' %}


{% block contend %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建靓号</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">

                            <label>{{ field.label }}</label>
                                    {{ field }}
                            <span style="color: red;"> {{ field.errors.0 }} </span>

                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">添 加</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app0326/templates/prettyNum_list.html
{% extends 'layout.html' %}

{% block contend %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/prettyNum/add/">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                新建靓号
            </a>
        </div>

       <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
          <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
          靓号列表
      </div>

      <!-- Table -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>号码</th>
            <th>价格</th>
            <th>级别</th>
            <th>状态</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
            {% for roe in PrettyNum %}
                <tr>
                    <th>{{ roe.id }}</th>
                    <th>{{ roe.mobile }}</th>
                    <td>{{ roe.price }}</td>
                    <td>{{ roe.get_level_display }}</td>
                    <td>{{ roe.get_status_display }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="#">编辑</a>
                        <a class="btn btn-danger btn-xs" href="#">删除</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>

    </div>
{% endblock %}

app0326/templates/user_add.html
{% extends 'layout.html' %}

{% block contend %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建员工</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">

                            <label>{{ field.label }}</label>
                                    {{ field }}
                            <span style="color: red;"> {{ field.errors.0 }} </span>

                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">添 加</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

app0326/templates/user_edit.html
{% extends 'layout.html' %}

{% block contend %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">编辑员工资料</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">

                            <label>{{ field.label }}</label>
                                    {{ field }}
                            <span style="color: red;"> {{ field.errors.0 }} </span>

                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">添 加</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

app0326/templates/user_list.html
{% extends 'layout.html' %}


{% block contend %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/user/add/">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                新建员工
            </a>
        </div>

       <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
          <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
          部门列表
      </div>

      <!-- Table -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>姓名</th>
            <th>密码</th>
            <th>年龄</th>
            <th>账户余额</th>
            <th>入职时间</th>
            <th>性别</th>
              <th>所属部门</th>
              <th>操作</th>
          </tr>
        </thead>
        <tbody>
            {% for roe in user_obj %}
                <tr>
                    <th>{{ roe.id }}</th>
                    <th>{{ roe.username }}</th>
                    <td>{{ roe.password }}</td>
                    <td>{{ roe.age }}</td>
                    <td>{{ roe.account }}</td>
                    <td>{{ roe.creat_time|date:"Y-m-d"}}</td>
                    <td>{{ roe.get_gener_display }}</td>
                    <td>{{ roe.depart.title }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/user/{{ roe.id }}/edit/">编辑</a>
                        <a class="btn btn-danger btn-xs" href="/user/{{ roe.id }}/del/">删除</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>

    </div>
{% endblock %}